server {
    listen 80;
    listen [::]:80;
    server_name unboxd.online www.unboxd.online;

    root /var/www/unboxd/current;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }
}
